P1/force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{0000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Label created</fullName>
                <default>true</default>
                <label>Label created</label>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Height in inches</description>
    <label>Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight in pounds</description>
    <label>Weight</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Width in inches</description>
    <label>Width</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UndeliveredPackages_CC.cls
public without sharing class UndeliveredPackages_CC {
    
    public List<UndeliveredPackages_Wrapper> wrapperList {
        get{
            if (wrapperList == null) {
                List<Mail__c> mailList = getMail(); 
                wrapperList = new List<UndeliveredPackages_Wrapper>();
                for (Mail__c mail : mailList) {
                    wrapperList.add(new UndeliveredPackages_Wrapper(mail.Name, mail.Address__c, mail.Weight__c, 
                                                                    mail.Height__c, mail.Width__c, mail.Insurance_Amount__c,
                                                                    mail.Delivery_Status__c));
                }
            }
            return wrapperList;
        }
        set;}

    // Get the mail & put it into the list.
    public static List<Mail__c> getMail() {
        System.debug('Entered getMail() method.');
        // Get current User object
        List<User> currentUserList = [SELECT ContactId FROM User WHERE Id=:UserInfo.getUserId()];
        User currentUser = currentUserList[0];
        // Find any mail associated with the Contact that the User is associated with.
        List<Mail__c> packageList = [SELECT Name, Weight__c, Height__c, Width__c, Address__c, Insurance_Amount__c, Delivery_Status__c 
                                     FROM Mail__c
                                     WHERE Inhabitant__r.Contact__c = :currentUser.ContactId  
                                     AND (Delivery_Status__c = 'Not Delivered'
                                     OR Delivery_Status__c = 'Missing')];
        System.debug('PackageList size: ' + packageList.size());
        return packageList;
    }
}