P1/force-app/main/default/objects/Address__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Street__c &amp; &quot;, &quot; &amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip_Code__c</formula>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{0000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/fields/ContactReal__c.field-meta.xml
<CustomField>
    <fullName>ContactReal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactReal</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Label created</fullName>
                <default>true</default>
                <label>Label created</label>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Destination</relationshipName>
    <type>Lookup</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Height in inches</description>
    <label>Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight in pounds</description>
    <label>Weight</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Width in inches</description>
    <label>Width</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/classes/CommunityController.cls
public without sharing class CommunityController {

    public CommunityController( ) {} 
    
        public List<UndeliveredPackages_Wrapper> undeliveredWrapperList {
        get{
            if (undeliveredWrapperList == null) {
                List<Mail__c> mailList = getMail(); 
                undeliveredWrapperList = new List<UndeliveredPackages_Wrapper>();
                for (Mail__c mail : mailList) {
                    undeliveredWrapperList.add(new UndeliveredPackages_Wrapper(mail.Name, mail.Destination__r.Mailing_Address__c, mail.Weight__c, 
                                                                    mail.Height__c, mail.Width__c, mail.Value__c,
                                                                    mail.Delivery_Status__c));
                }
            }
            return undeliveredWrapperList;
        }
        set;}
        
        public List<DeliveredPackages_Wrapper> wrapperListDelivered {
        get{
            if (wrapperListDelivered == null) {
                List<Mail__c> mailList = getDeliveredMail(); 
                wrapperListDelivered = new List<DeliveredPackages_Wrapper>();
                for (Mail__c mail : mailList) {
                    wrapperListDelivered.add(new DeliveredPackages_Wrapper(mail.Name, mail.Destination__r.Mailing_Address__c, mail.Weight__c, 
                                                                    mail.Height__c, mail.Width__c, mail.Value__c,
                                                                    mail.Delivery_Status__c));
                }
            }
            return wrapperListDelivered;
        }
        set;}

    // Get the mail & put it into the list.
    public static List<Mail__c> getMail() {
        System.debug('Entered getMail() method.');
        // Get current User object
        List<User> currentUserList = [SELECT ContactId FROM User WHERE Id=:UserInfo.getUserId()];
        User currentUser = currentUserList[0];
        // Find any mail associated with the Contact that the User is associated with.
        List<Mail__c> packageList = [SELECT Name, Weight__c, Height__c, Width__c, Destination__r.Mailing_Address__c, Value__c, Delivery_Status__c 
                                     FROM Mail__c
                                     WHERE ContactReal__c = :currentUser.ContactId  
                                     AND (Delivery_Status__c = 'In Transit'
                                     OR Delivery_Status__c = 'Missing'
                                     OR Delivery_Status__c = 'Label Created')];
        System.debug('PackageList size: ' + packageList.size());
        return packageList;
    }
   

    // Get the mail & put it into the list.
    public static List<Mail__c> getDeliveredMail() {
        System.debug('Entered getDeliveredMail() method.');
        List<User> currentUserList = [SELECT ContactId FROM User WHERE Id=:UserInfo.getUserId()];
        User currentUser = currentUserList[0];
        List<Mail__c> packageListDelivered = [SELECT Name, Weight__c, Height__c, Width__c, Destination__r.Mailing_Address__c, Value__c, Delivery_Status__c 
                                     FROM Mail__c
                                     WHERE ContactReal__c = :currentUser.ContactId  
                                     AND (Delivery_Status__c = 'Delivered')];
        System.debug('PackageList size: ' + packageListDelivered.size());
        return packageListDelivered;
    }
    
    public list <Account> acc {get;set;}
    public String searchKey {get;set;}


    public void searchRecords(){
    // Escaping Single Quotes Restricts user to string strings 
        List<Account> results = Database.query('SELECT Name, Industry, Phone, Type FROM Account WHERE Name like \'%' + searchKey + '%\' Limit 10');
        acc = results ;
    }
    public void clear(){
        acc.clear();
    }
    
    public String queryTrack {get;set;} 
        public list <Mail__c> track {get;set;}

 
    public void searchTrack(){
           if (queryTrack != ''){
            List<Mail__c> trackResults = Database.query('select Name, Delivery_Status__c from mail__c where name like \'' + queryTrack + '\'');
            track = trackresults;
        } 
    }  


        
 
    

}