P1/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P1/force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

P1/force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

P1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{0000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Label created</fullName>
                <default>true</default>
                <label>Label created</label>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Height in inches</description>
    <label>Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight in pounds</description>
    <label>Weight</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Width in inches</description>
    <label>Width</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UndeliveredPackages_DataFactory.cls
@isTest
public inherited sharing class UndeliveredPackages_DataFactory {

    @isTest
    public static void makeData() {

        // Create data for multiple users.

        List<User> userList = [SELECT Id, Name, ContactId FROM User
                               WHERE Name='Pepper *Stark'];
        User testUser = userList[0];
        
        List<User> userList2 = [SELECT Id, Name, ContactId FROM User
                                WHERE Name='Edna Frank'];
        User user2 = userList2[0];

        // Create addresses
        List<Address__c> addressList = new List<Address__c>();
        addressList.add(new Address__c(Street__c='100 Test St', City__c='Test', 
                                       State__c='NY', Zip_Code__c='12345'));
        addressList.add(new Address__c(Street__c='100 First St', City__c='Nowhere', 
                                       State__c='TX', Zip_Code__c='54321'));
        addressList.add(new Address__c(Street__c='200 AltTest St', City__c='Test', 
                                       State__c='NY', Zip_Code__c='12345'));

        insert addressList;

        // Create Contacts
        List<Contact> contactList = new List<Contact>();
        contactList.add(new Contact(FirstName='Pepper', LastName='*Stark', Salutation='Mrs.', MobilePhone='1112223333'));
        contactList.add(new Contact(FirstName='Edna', LastName='Frank', Salutation='Ms.', MobilePhone='2223334444'));

        insert contactList;

        // Create Inhabitants
        List<Inhabitant__c> inhabitantList = new List<Inhabitant__c>();
        inhabitantList.add(new Inhabitant__c(Contact__c=contactList[0].Id, Address__c=addressList[0].Id));
        inhabitantList.add(new Inhabitant__c(Contact__c=contactList[1].Id, Address__c=addressList[1].Id));
        inhabitantList.add(new Inhabitant__c(Contact__c=contactList[0].Id, Address__c=addressList[2].Id));

        insert inhabitantList;

        // Create undelivered Mail
        List<Mail__c> mailList = new List<Mail__c>();

        // Create mail for the first user with different delivery statuses.
        mailList.add(new Mail__c(Height__c=1, Weight__c=1, Width__c=1, 
                                 Delivery_Status__c='Not Delivered', Inhabitant__c=inhabitantList[0].Id));
        mailList.add(new Mail__c(Height__c=2, Weight__c=2, Width__c=2, 
                                 Delivery_Status__c='Missing', Inhabitant__c=inhabitantList[0].Id));
        mailList.add(new Mail__c(Height__c=3, Weight__c=3, Width__c=3, 
                                 Delivery_Status__c='Delivered', Inhabitant__c=inhabitantList[0].Id));

        // Create mail for the first user with a different Inhabitant value (i.e. a different address).
        mailList.add(new Mail__c(Height__c=1, Weight__c=1, Width__c=1, 
                                 Delivery_Status__c='Not Delivered', Inhabitant__c=inhabitantList[2].Id));

        // Create mail for the second user.
        mailList.add(new Mail__c(Height__c=4, Weight__c=1, Width__c=3, 
                     Delivery_Status__c='Not Delivered', Inhabitant__c=inhabitantList[1].Id));
        mailList.add(new Mail__c(Height__c=2, Weight__c=2, Width__c=2, 
                     Delivery_Status__c='Missing', Inhabitant__c=inhabitantList[1].Id));
        mailList.add(new Mail__c(Height__c=6, Weight__c=3, Width__c=10, 
                     Delivery_Status__c='Delivered', Inhabitant__c=inhabitantList[1].Id));

        // For the current version of the code, there should be 7 pieces of mail total.
        // Of those, only two should be visible for the user Pepper *Stark. 
        // Update: with 'Missing' included, 3 packages should be visible.
        insert mailList;

        // Create Cases
        List<Case> caseList = new List<Case>();
        caseList.add(new Case(Status='New', Origin='Email', ContactId=contactList[1].Id, Description='Belongs to Edna Frank'));
        caseList.add(new Case(Status='New', Origin='Email', ContactId=contactList[0].Id, Description='Belongs to Pepper *Stark'));
        caseList.add(new Case(Status='New', Origin='Email', ContactId=contactList[0].Id, Description='Also belongs to Pepper *Stark'));
        
        insert caseList;
    }

}